"""Add currencyrates table

Revision ID: 042c1cee347c
Revises: 7a4c3d1b580d
Create Date: 2020-11-21 14:18:30.779255

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "042c1cee347c"
down_revision = "7a4c3d1b580d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencyrates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("rate_to_kz", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencyrates")
    # ### end Alembic commands ###
