"""history_id to string

Revision ID: 62a6ee0d71b8
Revises: 39a75221d3ad
Create Date: 2020-11-22 21:47:04.541368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a6ee0d71b8'
down_revision = '39a75221d3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
