"""update tables

Revision ID: 7484826d5e85
Revises: 59ede24fe1f6
Create Date: 2020-11-20 19:15:52.397454

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7484826d5e85"
down_revision = "59ede24fe1f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("banks", sa.Column("date", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "date")
    op.drop_column("banks", "date")
    # ### end Alembic commands ###
