"""add location to products

Revision ID: 7a4c3d1b580d
Revises: 41f5780e496e
Create Date: 2020-11-21 12:40:06.937040

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a4c3d1b580d"
down_revision = "41f5780e496e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("location", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "location")
    # ### end Alembic commands ###
