"""history_id to string

Revision ID: dbbae8fc6274
Revises: 62a6ee0d71b8
Create Date: 2020-11-22 21:48:28.748143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbbae8fc6274'
down_revision = '62a6ee0d71b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gmailletters', 'history_id',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gmailletters', 'history_id',
               existing_type=mysql.VARCHAR(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
